sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - composer test-coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/code-coverage/clover/clover.xml

notifications:
  irc: "irc.freenode.org#noiselabs"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0be692024c564336df37
    on_success: change
    on_failure: always
    on_start: false